#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# MISC
#

# Ruby buildpack system configuration
update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
gem install bundler
