#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
xargs -L 1 git clone --depth=1 < /build/custom-buildpacks.txt
